services:
  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports: ["6379:6379"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 6

  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: campuslearn-api:latest
    restart: unless-stopped
    environment:
      NODE_ENV: "production"
      PORT: "5000"
      PUBLIC_URL: "http://localhost:5001"
      CORS_ORIGIN: "http://localhost:5173,http://localhost:5174,http://localhost:8080"
      
      # Database & Cache (Docker network)
      REDIS_URL: "redis://redis:6379"
      
      # Authentication
      JWT_SECRET: "test-jwt-secret-key-for-docker-testing-only-change-in-production"
      
      # Botpress (required for video calls)
      BOTPRESS_CLIENT_ID: "test-client-id"
      BOTPRESS_BOT_ID: "test-bot-id"
      BOTPRESS_PAT: "test-pat"
      BOTPRESS_WEBHOOK_URL: "http://localhost:5001/webhook"
      
      # CORS
      CORS_ORIGINS: "http://localhost:5173,http://localhost:8080,http://localhost:5001,http://localhost:3000"
      
      # Development URLs
      FRONTEND_URL: "http://localhost:5173"
      BACKEND_URL: "http://localhost:5001"
      
      # Test users
      TEST_USER_EMAIL: "test.student@student.belgiumcampus.ac.za"
      TEST_USER_PASSWORD: "password123"
      
      # Video call settings
      STUN_URLS: "stun:stun.l.google.com:19302,stun:stun1.l.google.com:19302"
      ENABLE_VIDEO_TRANSCODING: "false"
      VIDEO_COMPRESSION_ENABLED: "false"
      VIDEO_CACHE_TTL_SECONDS: "3000"
      VIDEO_QUALITIES: "720p,480p,360p"
      CDN_ENABLED: "false"
    ports:
      - "5001:5000"
    depends_on:
      redis:
        condition: service_healthy
