services:
  mongo:
    image: mongo:6
    restart: unless-stopped
    # For local dev tools (MongoDB Compass). Remove ports in prod.
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "mongosh --quiet --eval 'db.adminCommand({ ping: 1 }).ok' | grep 1",
        ]
      interval: 10s
      timeout: 5s
      retries: 6

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    # Expose for local debugging. Remove in prod if you want it internal-only.
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 6

  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: campuslearn-api:latest
    restart: unless-stopped
    environment:
      NODE_ENV: "production"
      PORT: "5000" # container listens here
      # PUBLIC_URL logging in server.ts
      PUBLIC_URL: "http://localhost:5001"
      # CORS: your frontend origins (comma-separated)
      CORS_ORIGIN: "http://localhost:5173,http://localhost:8080"
      # Internal service URLs
      MONGO_URL: "mongodb://mongo:27017/campuslearn"
      REDIS_URL: "redis://redis:6379"
    # host:container (dev runs on 5000)
    ports:
      - "${HOST_PORT-5001}:5000"
    depends_on:
      mongo:
        condition: service_healthy
      redis:
        condition: service_healthy

volumes:
  mongo_data:
