services:
  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports: ["6379:6379"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 6

  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: campuslearn-api:latest
    restart: unless-stopped
    environment:
      NODE_ENV: "production"
      PORT: "production5000"
      PUBLIC_URL: "http://localhost:5001"
      CORS_ORIGIN: "http://localhost:5173,http://localhost:5174,http://localhost:8080"
      
      # Database & Cache (override backend/.env for Docker network)
      MONGO_URL: "mongodb://mongo:27017/campuslearn"
      REDIS_URL: "redis://redis:6379"
      
      # JWT_SECRET and Botpress credentials come from backend/.env file (copied into container)
    ports:
      - "5001:5000"
    depends_on:
      redis:
        condition: service_healthy
